server:
  port: 6020

spring:
  datasource:
    url: jdbc:mysql://121.36.216.197:3306/tanyue?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20
      max-lifetime: 30000
      idle-timeout: 30000
      data-source-properties:
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        cachePrepStmts: true
        useServerPrepStmts: true
  rabbitmq:
    host: 121.36.216.197
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true #消息发送到交换机确认机制，是否确认回调
    publisher-returns: true #消息发送到交换机确认机制，是否返回回调
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1 #最小消费者数量
        max-concurrency: 5 #最大消费者数量
        retry:
          enabled: true #是否支持重试
  thymeleaf:
    cache: false
  redis:
    database: 0
    host: 121.36.216.197
    port: 6379
    password: 123456
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 8
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
    timeout: 10000
spring.redis.block-when-exhausted: true
#    lettuce:
#      pool:
#        max-active:  100 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 100 # 连接池中的最大空闲连接
#        min-idle: 50 # 连接池中的最小空闲连接
#        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      timeout: 1000

#mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.common.entity
  configLocation: classpath:mybatis-config.xml

#log4j配置
logging:
  config: classpath:log4j2-spring.xml

#腾讯云cos整合
cos:
  common:
    encrypt_access_key: 0
    bucket: tanyue-1307874331
    access_id: AKID83i7F6gz2oJYWDeqlQkuoW8c0FF5i5C3
    access_key: dz4sPgfOq2xbz2qNceQv96nDMDo9D0Xn
    region: ap-nanjing
    end_point: https://tanyue-1307874331.cos.ap-nanjing.myqcloud.com
    preview_queue: pd195a86a5b8b4e2a869334d474a36413
    rootPath: common

download:
  tempFilePath: /upload/temp